##############################################################################
# VoiceCode, a programming-by-voice environment
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# (C)2000, National Research Council of Canada
#
##############################################################################

#############################################################################
# Abbreviations needed for compiling public symbols of Python standard
# libraries
#############################################################################

from MediatorObject import add_abbreviation

add_abbreviation('abs', ['absolute'])
add_abbreviation('addr', ['address'])
add_abbreviation('alnum', ['all numeric', 'all numberical'])
add_abbreviation('alt', ['alternate', 'alternative'])
add_abbreviation('arg', ['argument'])
add_abbreviation('argv', ['arg V.', 'argument value'])
add_abbreviation('asc', ['ascii'])
add_abbreviation('atan', ['arc tangent'])
add_abbreviation('atof', ['A. to F.'])
add_abbreviation('atol', ['A. to L.'])
add_abbreviation('attr', ['attribute'])
add_abbreviation('avail', ['available'])
add_abbreviation('avg', ['average'])
add_abbreviation('beg', ['begin', 'beginning'])
add_abbreviation('bg', ['back ground'])
add_abbreviation('blk', ['block', 'blocking'])
add_abbreviation('buf', ['buffer'])
add_abbreviation('buff', ['buffer'])
add_abbreviation('builtin', ['built in'])
add_abbreviation('calc', ['calculate', 'calculated', 'calculation'])
add_abbreviation('cgi', ['C. G. I.'])
add_abbreviation('char', ['character'])
add_abbreviation('chdir', ['change dir', 'change directory'])
add_abbreviation('chg', ['change', 'changed'])
add_abbreviation('chmod', ['change mode'])
add_abbreviation('chr', ['character'])
add_abbreviation('clr', ['clear'])
add_abbreviation('cmd', ['command'])
add_abbreviation('cmp', ['compare'])
add_abbreviation('cntrl', ['control'])
add_abbreviation('col', ['column'])
add_abbreviation('concat', ['concatenate'])
add_abbreviation('conf', ['configure', 'configuration'])
add_abbreviation('config', ['configuration', 'configure'])
add_abbreviation('conn', ['connection', 'connected'])
add_abbreviation('cos', ['co sine'])
add_abbreviation('ctl', ['control'])
add_abbreviation('ctrl', ['control'])
add_abbreviation('cur', ['cursor', 'current'])
add_abbreviation('db', ['D. B.', 'data base'])
add_abbreviation('decl', ['declaration', 'declare'])
add_abbreviation('def', ['default', 'define'])
add_abbreviation('delim', ['delimiter'])
add_abbreviation('dev', ['develop', 'development', 'device'])
add_abbreviation('dict', ['dictionary'])
add_abbreviation('dir', ['directory', 'direction'])
add_abbreviation('div', ['divide'])
add_abbreviation('doc', ['document', 'documentation'])
add_abbreviation('dom', ['domain'])
add_abbreviation('dst', ['distance'])
add_abbreviation('dtd', ['D. T. D.'])
add_abbreviation('elem', ['element'])
add_abbreviation('ent', ['entry'])
add_abbreviation('env', ['environment'])
add_abbreviation('environ', ['environment'])
add_abbreviation('eol', ['E. O. L.', 'end of line'])
add_abbreviation('eval', ['E. val', 'evaluate'])
add_abbreviation('ex', ['example'])
add_abbreviation('exc', ['exception'])
add_abbreviation('exec', ['execute', 'executable'])
add_abbreviation('expr', ['expression'])
add_abbreviation('fg', ['foreground'])
add_abbreviation('fifo', ['first in first out'])
add_abbreviation('fmt', ['format'])
add_abbreviation('fp', ['file pointer'])
add_abbreviation('func', ['function'])
add_abbreviation('gid', ['G. I. D.', 'group I. D.'])
add_abbreviation('glob', ['global'])
add_abbreviation('goto', ['go to'])
add_abbreviation('gr', ['group'])
add_abbreviation('hex', ['hexadecimal'])
add_abbreviation('html', ['H. T. M. L.'])
add_abbreviation('http', ['H. T. T. P.'])
add_abbreviation('imap', ['I. map'])
add_abbreviation('impl', ['implementation'])
add_abbreviation('incl', ['include', 'included'])
add_abbreviation('info', ['information'])
add_abbreviation('init', ['intial', 'initialize'])
add_abbreviation('ins', ['insert'])
add_abbreviation('int', ['integer'])
add_abbreviation('intro', ['introduction'])
add_abbreviation('io', ['I. O.'])
add_abbreviation('ip', ['I. P.'])
add_abbreviation('lambd', ['lambda'])
add_abbreviation('len', ['length'])
add_abbreviation('ln', ['line'])
add_abbreviation('lnk', ['link'])
add_abbreviation('loc', ['location'])
add_abbreviation('login', ['log in'])
add_abbreviation('mem', ['memory'])
add_abbreviation('mk', ['make'])
add_abbreviation('mnt', ['mount', 'mounted'])
add_abbreviation('mod', ['mode', 'modify'])
add_abbreviation('msec', ['millisecond'])
add_abbreviation('msg', ['message'])
add_abbreviation('nam', ['name'])
add_abbreviation('nntp', ['N. N. T. P.'])
add_abbreviation('no', ['number'])
add_abbreviation('num', ['number'])
add_abbreviation('obj', ['object'])
add_abbreviation('oct', ['octal'])
add_abbreviation('opt', ['optional', 'option', 'optimize'])
add_abbreviation('osf', ['O. S. F.'])
add_abbreviation('par', ['parameter'])
add_abbreviation('param', ['parameter'])
add_abbreviation('pat', ['pattern'])
add_abbreviation('perm', ['permission'])
add_abbreviation('pkg', ['package'])
add_abbreviation('pos', ['position'])
add_abbreviation('proto', ['prototype', 'protocol'])
add_abbreviation('pty', ['P. T. Y.'])
add_abbreviation('punct', ['punctuation'])
add_abbreviation('py', ['P. Y.', 'python'])
add_abbreviation('rand', ['random'])
add_abbreviation('rd', ['read'])
add_abbreviation('rect', ['rectangle'])
add_abbreviation('ref', ['reference'])
add_abbreviation('reg', ['regular', 'regular expression'])
add_abbreviation('rel', ['relative'])
add_abbreviation('repr', ['represent', 'representation'])
add_abbreviation('req', ['request'])
add_abbreviation('rexp', ['regular expression'])
add_abbreviation('rgb', ['R. G. B.'])
add_abbreviation('rm', ['remove'])
add_abbreviation('scr', ['screen'])
add_abbreviation('sec', ['second'])
add_abbreviation('sep', ['separator'])
add_abbreviation('seq', ['sequence'])
add_abbreviation('serv', ['server'])
add_abbreviation('sig', ['signal', 'special interest group'])
add_abbreviation('sin', ['sine'])
add_abbreviation('smtp', ['S. M. T. P.'])
add_abbreviation('sock', ['socket'])
add_abbreviation('soundex', ['soundex'])
add_abbreviation('spc', ['space'])
add_abbreviation('src', ['source'])
add_abbreviation('stat', ['statistic', 'static'])
add_abbreviation('stdin', ['S. T. D. in', 'standard input'])
add_abbreviation('str', ['string'])
add_abbreviation('sub', ['sub routine'])
add_abbreviation('sym', ['symbol'])
add_abbreviation('sync', ['synchronize'])
add_abbreviation('temp', ['temporary'])
add_abbreviation('termid', ['term I. D.', 'terminal I. D.'])
add_abbreviation('tmp', ['temporary'])
add_abbreviation('tok', ['token'])
add_abbreviation('trans', ['transition', 'transport', 'transform', 'transformation'])
add_abbreviation('tty', ['T. T. Y.'])
add_abbreviation('uid', ['U. I. D.', 'user I. D.'])
add_abbreviation('uniq', ['unique'])
add_abbreviation('url', ['U. R. L.'])
add_abbreviation('uu', ['U. U.'])
add_abbreviation('var', ['variable'])
add_abbreviation('win', ['window'])
add_abbreviation('xml', ['X. M. L.'])
