import exceptions, sys

class SelfHandlingExc(Exception):
    """Self handling exceptions.

    This class of exception comes with a method for handling itself.

    **INSTANCE ATTRIBUTE**

    *STR* type -- Error type
    - *'FATAL'* -> exit after handling error
    - *'WARNING'* -> do not exit after handing error
    *???* error_file -- file where to output error message

    **CLASS ATTRIBUTE**

    *none* -- 
    """

    def __init__(self, type='FATAL'):
        """Constructor

        **INPUTS**

        *INT* type='FATAL' -- value of attribute of same name 

        **OUTPUTS**

        *none* -- 
        """
        self.__dict__['type'] = type

    def handle(self, **args):
        """Self handler for the exception

        **INPUTS**

        *ANY* **args -- List of Key=Value arguments used to
         override the default attributes of the exception.

        **OUTPUTS**

        *none* -- 
        """
        self.__init__(args)
        self.err_file.write(self.type + ": " + self.err_message() + "\n")
        self.maybe_exit()

    def err__message(self):
        """Error message generated by exception.

        **INPUTS**

        *none* -- 

        **OUTPUTS**

        *STR* mess -- Error message
        """
        mess = "SelfHandlingExc was raised"
        return mess

    def maybe_exit(self):
        """Exits the program if this is a fatal exception

        **INPUTS**

        *none* -- 

        **OUTPUTS**

        *none* -- 
        """
        if (self.type == "FATAL"):
            exit


if (__name__ == "__main__"):
    try:
        raise SelfHandlingExc(type='WARNING')
    except SelfHandlingExc, exc:
        exc.handle()

    try:
        raise SelfHandlingExc(type='FATAL')
    except SelfHandlingExc, exc:
        exc.handle()

    sys.stdout.write('This message should not be printed\n')
    
        

